#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    speedDial,      sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           mFlyRF,        tmotorVex393TurboSpeed_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port5,           mFlyLB,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           mFlyRB,        tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           mFlyLF,        tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
