#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    vPowerExpander, sensorAnalog)
#pragma config(Sensor, in2,    speedDial,      sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port4,           mFlyBottom,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mFlyMidBottom, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           mFlyMidTop,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           mFlyTop,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){}
