#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    speedDial,      sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           mFlyB,         tmotorVex393TurboSpeed_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port5,           mFlyM,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          mFlyT,         tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
